### ISSUE TITLE
Plugin not working with Kodi 20.1

### ISSUE THREAD

**Issue by Soupstraw** [aanderse/plugin.program.steam.library#34]
When I try to open the steam library in Kodi 20.1, I get this error:
```
2023-05-28 15:44:40.111 T:1493    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: module 'xbmc' has no attribute 'translatePath'
                                                   Traceback (most recent call last):
                                                     File "/nix/store/49db0yqapgcvmd4p123hjb0x21jkpga8-kodi-20.1-env/share/kodi/addons/plugin.program.steam.library/addon.py", line 2, in <module>
                                                       from resources import main
                                                     File "/nix/store/49db0yqapgcvmd4p123hjb0x21jkpga8-kodi-20.1-env/share/kodi/addons/plugin.program.steam.library/resources/main.py", line 6, in <module>
                                                       from . import arts
                                                     File "/nix/store/49db0yqapgcvmd4p123hjb0x21jkpga8-kodi-20.1-env/share/kodi/addons/plugin.program.steam.library/resources/arts.py", line 16, in <module>
                                                       addonUserDataFolder = xbmc.translatePath(__addon__.getAddonInfo('profile'))
                                                   AttributeError: module 'xbmc' has no attribute 'translatePath'
                                                   -->End of Python script error report<--
```

I think this plugin is [relying on a deprecated function](https://github.com/teeedubb/teeedubb-xbmc-repo/issues/24).

**Comment by aanderse** [comment]
Thanks @Soupstraw! I'll try to look at this later in the week.

**Comment by aanderse** [comment]
Sorry for the delay, but all should be good now. Thanks again for reporting.
